# Generated by Django 3.1.6 on 2021-02-18 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210218_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(default='0000000000', max_length=15),
        ),
    ]
