# Generated by Django 3.1.6 on 2021-02-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210218_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='product',
        ),
        migrations.AddField(
            model_name='favorite',
            name='customerId',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='favorite',
            name='productId',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
