# Generated by Django 3.1.6 on 2021-02-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20210219_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='productId',
        ),
        migrations.AddField(
            model_name='favorite',
            name='product_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
