# Generated by Django 3.1.6 on 2021-02-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20210219_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='favoriteId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
