# Generated by Django 3.1.6 on 2021-02-23 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_product_is_in_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_in_favorite',
        ),
    ]
