# Generated by Django 3.1.6 on 2021-02-25 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_product_is_in_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='state',
            new_name='region',
        ),
    ]
